name: Echidna

on: [push, pull_request]

jobs:
  echidna:
    name: Echidna
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testName:
          - MakerBadgesEchidnaTest
          - TokenId

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --no-progress --non-interactive --frozen-lockfile

      - name: Compile
        run: yarn build

      - name:
        uses: crytic/echidna-action@v1
        with:
          solc-version: 0.7.6
          files: .
          contract: TokenEchidna
          crytic-args: --hardhat-ignore-compile

        - name: Fuzz ${{ matrix.testName}}
          uses: crytic/echidna-action@v1
          with:
            files: .
            contract: ${{ matrix.testName }}
            config: echidna.config.ci.yml
            format: text
            check-asserts: true
            test-limit: 50000
            seq-len: 100
            solc-version: 0.8.4
            crytic-args: --hardhat-ignore-compile
